#!/bin/bash

# Docker
alias dps="sudo docker ps"

# Miscellaneous
alias todo="vim ~/notes/tasklist.md"

# Alias Over-writes
# Plugins from Oh-My-Zsh may use create their own aliases. Define them here to  
#  make sure your alias takes precedence.
#
#alias gs='git status'  # This ensures that gs refers to Git, and not GhostScript

