#!/bin/bash

# Quick Jumps
alias proj="cd ~/proj"
alias notes="cd ~/notes"

# Docker
alias dps='docker ps'

# Miscellaneous
alias todo='vim ~/notes/tasklist.md'

# Overwrites 'gs' as "GhostScript"
alias gs='git status'

# Easter Eggs
alias rtfm='man'
